"""Brief routes — PDF export and public share links.

PDF uses fpdf2 (pure Python, zero system dependencies, works on Windows).
"""

import asyncio
from datetime import datetime, timezone

from fastapi import APIRouter, HTTPException
from fastapi.responses import Response

from database import client as db

router = APIRouter(tags=["briefs"])


# ── PDF generation (fpdf2) ────────────────────────────────────────────────────

_UNICODE_MAP = str.maketrans({
    "—": "--",  # em dash
    "–": "-",   # en dash
    "‘": "'",   # left single quote
    "’": "'",   # right single quote
    "“": '"',   # left double quote
    "”": '"',   # right double quote
    "…": "...", # ellipsis
    "•": "-",   # bullet
    "→": "->",  # right arrow
    "·": ".",   # middle dot
    "é": "e",   # e acute
    "à": "a",   # a grave
    "è": "e",   # e grave
})


def _s(text: str | None) -> str:
    """Sanitize to Latin-1 safe ASCII for fpdf2 core fonts."""
    if not text:
        return ""
    return text.translate(_UNICODE_MAP).encode("latin-1", errors="replace").decode("latin-1")


_MOVE_RGB: dict[str, tuple[int, int, int]] = {
    "ATTACK":   (239,  68,  68),
    "DEFEND":   (245, 158,  11),
    "ESCALATE": (220,  38,  38),
    "WAIT":     (113, 113, 122),
    "MONITOR":  ( 56, 189, 248),
}


class _BriefPDF:
    """fpdf2 wrapper with persistent header and footer on every page."""

    def __init__(self, generated_at: str):
        from fpdf import FPDF

        _generated_at = generated_at  # captured for footer closure

        class _PDF(FPDF):
            def header(self_inner):
                lm = self_inner.l_margin
                pw = self_inner.epw
                self_inner.set_font("Courier", "B", 9)
                self_inner.set_text_color(40, 40, 40)
                self_inner.set_x(lm)
                self_inner.cell(pw / 2, 5, "StratOS AI", ln=False)
                self_inner.set_font("Courier", "", 8)
                self_inner.set_text_color(150, 150, 150)
                self_inner.set_x(lm + pw / 2)
                self_inner.cell(pw / 2, 5, "EXECUTIVE BATTLE BRIEF", align="R", ln=True)
                self_inner.set_draw_color(210, 210, 210)
                self_inner.set_line_width(0.2)
                self_inner.line(lm, self_inner.get_y(), lm + pw, self_inner.get_y())
                self_inner.ln(5)

            def footer(self_inner):
                self_inner.set_y(-14)
                lm = self_inner.l_margin
                pw = self_inner.epw
                self_inner.set_draw_color(210, 210, 210)
                self_inner.set_line_width(0.2)
                self_inner.line(lm, self_inner.get_y(), lm + pw, self_inner.get_y())
                self_inner.ln(1)
                self_inner.set_font("Courier", "I", 7)
                self_inner.set_text_color(160, 160, 160)
                page_info = (
                    "Generated by StratOS AI - Powered by Bright Data - "
                    + _generated_at
                    + " - Page "
                    + str(self_inner.page_no())
                    + " of {nb}"
                )
                self_inner.cell(0, 5, page_info, align="C")

        self._pdf = _PDF()
        self._pdf.alias_nb_pages()
        self._pdf.set_auto_page_break(auto=True, margin=22)
        self._pdf.set_margins(20, 20, 20)

    @property
    def pdf(self):
        return self._pdf


def _generate_pdf(analysis: dict, brief: dict) -> bytes:
    action_pack = brief.get("action_pack") or {}
    actions = action_pack.get("actions") or {}
    provider_calls_raw: list[dict] = brief.get("provider_calls") or []

    # Aggregate provider calls by product.
    product_counts: dict[str, dict] = {}
    for call in provider_calls_raw:
        prod = call.get("product", "unknown")
        if prod not in product_counts:
            product_counts[prod] = {"count": 0, "ok": 0}
        product_counts[prod]["count"] += 1
        if call.get("ok"):
            product_counts[prod]["ok"] += 1

    target       = _s(analysis.get("target", ""))
    analysis_type = _s(analysis.get("analysis_type", "").replace("_", " ").upper())
    analysis_id   = str(analysis.get("id", ""))
    score        = brief.get("market_move_score", 0)
    move         = _s((brief.get("recommended_move") or "MONITOR").upper())
    confidence   = brief.get("confidence_score", 0)
    headline     = _s(action_pack.get("headline", ""))
    situation    = _s(action_pack.get("situation", ""))
    rationale    = _s(action_pack.get("coordinator_rationale", ""))
    immediate    = [_s(x) for x in (actions.get("immediate") or [])]
    this_week    = [_s(x) for x in (actions.get("this_week") or [])]
    watch        = [_s(x) for x in (actions.get("watch") or [])]
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    doc = _BriefPDF(generated_at)
    pdf = doc.pdf
    pdf.add_page()

    lm = pdf.l_margin
    pw = pdf.epw   # effective page width

    # ── Analysis metadata strip ────────────────────────────────────────────────
    pdf.set_font("Courier", "", 7)
    pdf.set_text_color(150, 150, 150)
    meta = f"TARGET: {target}   |   {analysis_type}   |   ANALYSIS {analysis_id[:8].upper()}   |   {generated_at}"
    pdf.cell(0, 4, meta, ln=True)
    pdf.ln(4)

    # ── Score / Move / Confidence banner ──────────────────────────────────────
    banner_h = 26
    by = pdf.get_y()
    pdf.set_fill_color(16, 16, 16)
    pdf.rect(lm, by, pw, banner_h, style="F")

    score_rgb = (239, 68, 68) if score >= 80 else (245, 158, 11) if score >= 60 else (200, 200, 200)

    # Score
    pdf.set_xy(lm + 6, by + 3)
    pdf.set_font("Courier", "", 7)
    pdf.set_text_color(110, 110, 110)
    pdf.cell(50, 4, "MARKET MOVE SCORE", ln=True)
    pdf.set_xy(lm + 6, by + 8)
    pdf.set_font("Courier", "B", 22)
    pdf.set_text_color(*score_rgb)
    pdf.cell(50, 15, str(score))

    # Move
    move_rgb = _MOVE_RGB.get(move, (200, 200, 200))
    pdf.set_xy(lm + 68, by + 3)
    pdf.set_font("Courier", "", 7)
    pdf.set_text_color(110, 110, 110)
    pdf.cell(50, 4, "RECOMMENDED MOVE", ln=True)
    pdf.set_xy(lm + 68, by + 10)
    pdf.set_font("Courier", "B", 13)
    pdf.set_text_color(*move_rgb)
    pdf.cell(60, 10, move)

    # Confidence
    pdf.set_xy(lm + 140, by + 3)
    pdf.set_font("Courier", "", 7)
    pdf.set_text_color(110, 110, 110)
    pdf.cell(30, 4, "CONFIDENCE", ln=True)
    pdf.set_xy(lm + 140, by + 8)
    pdf.set_font("Courier", "B", 16)
    pdf.set_text_color(220, 220, 220)
    pdf.cell(30, 15, f"{confidence}/100")

    pdf.set_xy(lm, by + banner_h + 6)

    # ── Situation ─────────────────────────────────────────────────────────────
    if headline:
        pdf.set_font("Courier", "B", 7)
        pdf.set_text_color(130, 130, 130)
        pdf.cell(0, 4, "SITUATION", ln=True)
        pdf.ln(2)
        pdf.set_font("Courier", "B", 11)
        pdf.set_text_color(20, 20, 20)
        pdf.multi_cell(0, 6, headline, align="L")
        if situation:
            pdf.ln(2)
            pdf.set_font("Courier", "", 9)
            pdf.set_text_color(80, 80, 80)
            pdf.multi_cell(0, 6, situation, align="L")
        pdf.ln(5)

    # ── Divider ───────────────────────────────────────────────────────────────
    def divider():
        pdf.set_draw_color(220, 220, 220)
        pdf.set_line_width(0.2)
        pdf.line(lm, pdf.get_y(), lm + pw, pdf.get_y())
        pdf.ln(5)

    divider()

    # ── Action sections — vertical flow ───────────────────────────────────────
    def action_section(label: str, color_rgb: tuple, items: list[str]):
        if not items:
            return
        pdf.set_font("Courier", "B", 8)
        pdf.set_text_color(*color_rgb)
        pdf.cell(0, 5, label, ln=True)
        pdf.ln(1)
        pdf.set_font("Courier", "", 9)
        pdf.set_text_color(60, 60, 60)
        for item in items:
            # Arrow prefix in accent color
            pdf.set_text_color(*color_rgb)
            pdf.set_x(lm)
            pdf.cell(6, 6, "->")
            pdf.set_text_color(60, 60, 60)
            pdf.multi_cell(pw - 6, 6, item, align="L")
        pdf.ln(4)

    action_section("IMMEDIATE", (210, 50, 50), immediate)
    action_section("THIS WEEK", (200, 130, 10), this_week)
    action_section("WATCH",     ( 30, 160, 210), watch)

    divider()

    # ── Coordinator rationale ───────────────────────────────────────────────────
    if rationale:
        pdf.set_font("Courier", "B", 7)
        pdf.set_text_color(130, 130, 130)
        pdf.cell(0, 4, "COORDINATOR RATIONALE", ln=True)
        pdf.ln(2)
        pdf.set_font("Courier", "", 9)
        pdf.set_text_color(90, 90, 90)
        pdf.multi_cell(0, 6, rationale, align="L")
        pdf.ln(5)
        divider()

    # ── Bright Data product chips ─────────────────────────────────────────────
    if product_counts:
        pdf.set_font("Courier", "B", 7)
        pdf.set_text_color(130, 130, 130)
        pdf.cell(0, 4, "POWERED BY BRIGHT DATA - INTELLIGENCE SOURCES", ln=True)
        pdf.ln(3)

        chip_w = 34
        chip_h = 14
        gap = 3
        bx = lm
        cy = pdf.get_y()

        for prod, info in sorted(product_counts.items()):
            # Light gray chip with border
            pdf.set_fill_color(245, 245, 245)
            pdf.set_draw_color(210, 210, 210)
            pdf.set_line_width(0.3)
            pdf.rect(bx, cy, chip_w, chip_h, style="FD")

            # Count in red
            pdf.set_xy(bx + 2, cy + 2)
            pdf.set_font("Courier", "B", 11)
            pdf.set_text_color(200, 50, 50)
            pdf.cell(8, 6, str(info["count"]))

            # Product label in dark
            prod_label = prod.replace("_", " ").upper()
            if len(prod_label) > 9:
                prod_label = prod_label[:9]
            pdf.set_xy(bx + 2, cy + 8)
            pdf.set_font("Courier", "", 6)
            pdf.set_text_color(50, 50, 50)
            pdf.cell(chip_w - 4, 4, prod_label)

            bx += chip_w + gap
            if bx + chip_w > lm + pw:  # wrap to next row
                bx = lm
                cy += chip_h + gap

        pdf.set_xy(lm, cy + chip_h + 4)

    return bytes(pdf.output())


# ── Routes ────────────────────────────────────────────────────────────────────

@router.get("/analyses/{analysis_id}/brief/pdf")
async def download_brief_pdf(analysis_id: str) -> Response:
    """Render the battle brief as a downloadable PDF via fpdf2."""
    analysis = await db.aget_analysis(analysis_id)
    if not analysis:
        raise HTTPException(status_code=404, detail="Analysis not found")
    brief = await db.aget_brief_by_analysis(analysis_id)
    if not brief:
        raise HTTPException(status_code=404, detail="Brief not ready yet")

    try:
        pdf_bytes = await asyncio.to_thread(_generate_pdf, analysis, brief)
    except ImportError:
        raise HTTPException(
            status_code=503,
            detail="PDF generation unavailable. Run: uv add fpdf2",
        )

    target_slug = analysis.get("target", "brief").replace(".", "-").replace("/", "-")
    filename = f"stratos-brief-{target_slug}-{analysis_id[:8]}.pdf"

    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.post("/analyses/{analysis_id}/brief/share")
async def share_brief(analysis_id: str) -> dict:
    """Mark a brief as publicly shared. Returns the public share URL."""
    analysis = await db.aget_analysis(analysis_id)
    if not analysis:
        raise HTTPException(status_code=404, detail="Analysis not found")
    brief = await db.aget_brief_by_analysis(analysis_id)
    if not brief:
        raise HTTPException(status_code=404, detail="Brief not ready yet")

    await db.amark_brief_shared(analysis_id)
    return {"share_url": f"/share/{analysis_id}"}


@router.get("/share/{analysis_id}")
async def get_shared_brief(analysis_id: str) -> dict:
    """Public read-only endpoint for a shared battle brief."""
    analysis = await db.aget_analysis(analysis_id)
    if not analysis:
        raise HTTPException(status_code=404, detail="Not found")
    brief = await db.aget_brief_by_analysis(analysis_id)
    if not brief:
        raise HTTPException(status_code=404, detail="Not found")
    return {"analysis": analysis, "brief": brief}
