"""Guard tests for sample-brief provenance and date handling.

These protect against regressions where a deterministic demo fixture starts implying
false currency (e.g. claiming to be a live/real run) or drops its provenance/date
metadata. They read the Markdown fixtures directly and need no external credentials.

Run from the api/ directory:
    PYTHONPATH=. uv run pytest tests/test_brief_provenance.py -v
"""

import re
from datetime import date
from pathlib import Path

import pytest

# repo_root/docs/sample-briefs — this file is at repo_root/api/tests/
BRIEFS_DIR = Path(__file__).resolve().parents[2] / "docs" / "sample-briefs"

# Markdown brief fixtures = every .md in the folder except the explanatory README.
BRIEF_FILES = sorted(p for p in BRIEFS_DIR.glob("*.md") if p.name.lower() != "readme.md")

REQUIRED_PROVENANCE_FIELDS = [
    "**Mode**",
    "**Analysis executed**",
    "**Facts as-of**",
    "**Fixture last verified**",
]

REQUIRED_STRUCTURE_MARKERS = [
    "DETERMINISTIC DEMO FIXTURE",  # explicit mode label
    "Evidence",                    # evidence section
    "Inference",                   # inference section
    "Recommendation",              # recommendation (Coordinator Rationale)
    "Confidence",                  # confidence appears in the metric table
]

# Phrases that would assert false currency — a fixture must NEVER claim to be a live/real run.
FORBIDDEN_CLAIMS = [
    r"not\s+mocked",
    r"this is a real brief",
    r"real brief generated",
    r"generated by the live system",
]

_DATE_ROW = r"\|\s*\*\*{label}\*\*\s*\|\s*(\d{{4}}-\d{{2}}-\d{{2}})"


def test_brief_fixtures_exist():
    assert BRIEF_FILES, f"No brief fixtures found in {BRIEFS_DIR}"


def test_readme_present():
    assert (BRIEFS_DIR / "README.md").exists(), "sample-briefs/README.md (fixture guide) is missing"


@pytest.mark.parametrize("path", BRIEF_FILES, ids=lambda p: p.name)
def test_brief_has_provenance_header(path: Path):
    text = path.read_text(encoding="utf-8")
    for field in REQUIRED_PROVENANCE_FIELDS:
        assert field in text, f"{path.name} is missing provenance field {field!r}"


@pytest.mark.parametrize("path", BRIEF_FILES, ids=lambda p: p.name)
def test_brief_has_structure_markers(path: Path):
    text = path.read_text(encoding="utf-8")
    for marker in REQUIRED_STRUCTURE_MARKERS:
        assert marker in text, f"{path.name} is missing required marker {marker!r}"


@pytest.mark.parametrize("path", BRIEF_FILES, ids=lambda p: p.name)
def test_brief_makes_no_false_currency_claim(path: Path):
    text = path.read_text(encoding="utf-8").lower()
    for pattern in FORBIDDEN_CLAIMS:
        assert re.search(pattern, text) is None, (
            f"{path.name} contains a false-currency claim matching {pattern!r} — "
            "fixtures must never claim to be a live or real run"
        )


@pytest.mark.parametrize("path", BRIEF_FILES, ids=lambda p: p.name)
def test_brief_dates_are_iso_and_ordered(path: Path):
    text = path.read_text(encoding="utf-8")

    facts = re.search(_DATE_ROW.format(label="Facts as-of"), text)
    verified = re.search(_DATE_ROW.format(label="Fixture last verified"), text)

    assert facts, f"{path.name} has no parseable 'Facts as-of' ISO date (YYYY-MM-DD)"
    assert verified, f"{path.name} has no parseable 'Fixture last verified' ISO date"

    facts_date = date.fromisoformat(facts.group(1))
    verified_date = date.fromisoformat(verified.group(1))

    # A fixture cannot have been "last verified" before its facts were captured.
    assert facts_date <= verified_date, (
        f"{path.name}: 'Facts as-of' ({facts_date}) is after "
        f"'Fixture last verified' ({verified_date})"
    )
